name: mini_trainer
channels:
  - conda-forge
dependencies:
  - python >=3.11,<3.13
  - pytorch
  - torchvision
  - torchaudio
  - matplotlib
  - tqdm
  - psutil
  - micromamba install setuptools"<=81.0.0" # Temporary fix to the error "ModuleNotFoundError: No module named 'pkg_resources'" from tensorboard
  - tensorboard
  - pandas
  - zarr
  - scipy
  - pyarrow