import os
import random
import sys
from argparse import ArgumentParser
from typing import Any

import numpy as np
import torch

from mini_trainer import Formatter, TQDM
from mini_trainer.builders import AutoEmbedder, BaseBuilder
from mini_trainer.config import (defaults_from_function, dump_resolved_config,
                                 load_yaml_config, merge_dicts,
                                 restructure_cli_args)
from mini_trainer.utils import increment_name_dir
from mini_trainer.utils.augmentation import debug_augmentation
from mini_trainer.utils.data import auto_find_images, get_metadata
from mini_trainer.utils.logging import BaseResultCollector

def assign_model_from_folder(folder : str, args : dict[str, Any]):
    # Traverse and parse folder
    train_config = os.path.join(folder, "config.yaml")
    if not os.path.exists(train_config):
        raise FileNotFoundError(f'Model folder ({folder}) does not contain a config file (config.yaml).')
    
    class_spec = os.path.join(folder, "class_spec.json")
    if not os.path.exists(class_spec):
        raise FileNotFoundError(f'Model folder ({folder}) does not contain a class specification file (class_spec.json).')
    
    weight_folder = os.path.join(folder, "weights")
    if not os.path.exists(weight_folder):
        raise FileNotFoundError(f'Model folder ({folder}) does not contain a weight directory (weights).')
    model_weights = os.path.join(weight_folder, "best.pt")
    if not os.path.exists(model_weights):
        raise FileNotFoundError(f'Model weight folder ({model_weights}) does not contain a best weight file (best.pt).')
    
    train_args = load_yaml_config(train_config)
    model_args = train_args.get("model_builder_kwargs", None)
    if model_args is None:
        raise KeyError(f'Model config file ({train_config}) does not contain model building arguments (model_builder_kwargs).')
    
    # Assign arguments
    args["class_spec"] = args.get("class_spec", None) or class_spec
    args["model_builder_kwargs"].update(model_args)
    args["model_builder_kwargs"]["weights"] = args["model_builder_kwargs"].get("weights", None) or model_weights
    args["name"] = args.get("name", None) or os.path.split(folder)[1]

    return args

def main(
        input : str,
        output : str | None=None,
        threshold : float=0,
        class_spec : str | None=None,
        data_index : str | None=None,
        name: str | None=None,
        subsample : int | None=None,
        device : str="cuda:0",
        dtype : str="bfloat16",
        seed : int | None=None,
        builder : type[BaseBuilder]=BaseBuilder,
        collector_cls : type[BaseResultCollector]=BaseResultCollector,
        spec_model_dataloader_kwargs : dict[str, Any]={},
        model_builder_kwargs : dict[str, Any]={
            "model_type" : "efficientnet_v2_s",
            "weights" : None,
            "fine_tune" : False,
            "hidden" : True,
            "droprate" : 0.1,
            "normalized" : True
        },
        dataloader_builder_kwargs : dict[str, Any]={
            "batch_size" : 16,
            "resize_size" : 256
        },
        augmentation_builder_kwargs : dict[str, Any]={},
        criterion_builder_kwargs : dict[str, Any]={},
        collector_cls_kwargs : dict[str, Any]={}
    ):
    """
    Predict with a classifier.

    Args:
        input: Path to a directory containing a subdirectory for each class, where
            each subdirectory's name corresponds to the class name.
            It is also possible to pass the path to a parquet as generated by `gbifxdl` instead of a directory.
        output: Root directory for all created files and directories.
            Default is current working directory ``'.'``.
        class_spec: Path to a JSON file containing the mapping from class names to indices
            and other important information necessary to construct compatible models and dataloaders.
            If the file does not exist, it will be created based on subdirectories
            found under `output` if it is set. Default is 'class_index.json'.
        epochs: Number of training epochs. Default is 15.
        name: Name of the output model. If not provided, a descriptive name
            will be inferred from other arguments. Default is ``None``.
        device: Device used for training (e.g., ``'cuda:0'``, ``'cpu'``). Default is ``'cuda:0'``.
        dtype: PyTorch data type for images during training and validation (e.g., ``'bfloat16'``). 
            The model parameters are always stored in float32 with training AMP. 
            Default is ``'bfloat16'``.
        seed: Initial seed for Python's random number generator to ensure reproducibility,
            especially for train/validation splits. Default is ``None``.
        builder: An object inheriting from ``mini_trainer.builders.BaseBuilder``. 
            This object is responsible for instantiating the model, dataloader, augmentation, 
            optimizer, scaler, EMA, criterion (loss function) and learning rate scheduler.
        **kwargs:
            Additional arguments are passed to the various builder methods.
            See ``mini_trainer.builders.BaseBuilder`` for details.
    """
    orig_args = locals()
    # Prepare state    
    if seed is not None:
        random.seed(seed)
        np.random.seed(seed)
        torch.manual_seed(seed)
    if name is None:
        name = "train"
    name = increment_name_dir(name, output)

    input = os.path.abspath(input)
    output_dir = None if output is None else os.path.abspath(os.path.join(output, name))
    if output_dir is not None:
        try:
            os.makedirs(output_dir, exist_ok=False)
        except OSError as e:
            e.add_note(f"Training output directory already exists: {output_dir}. Perhaps a run of with the `{name=}` already exists?")

    device : torch.device = torch.device(device)
    dtype : torch.dtype = getattr(torch, dtype.removeprefix("torch.").strip().lower())

    # Dump resolved configuration using locals and normalized values
    dump_resolved_config(
        output_dir=output_dir,
        fn=main,
        local_vars=orig_args,
        overrides={
            "input": input,
            "output": output_dir,
            "device": device,
            "dtype": dtype,
            "name": name,
        },
    )

    # Load additional information for model and dataloader instantiation
    # e.g. number of classes, class-to-index dictionary
    class_spec = builder.class_spec(
        path=class_spec if class_spec is not None else os.path.join(output_dir, "class_spec.json"), 
        dir=input,
        **spec_model_dataloader_kwargs
    )

    # Prepare model
    nn_model, model_preprocess = builder.build_model(
        device=device, 
        dtype=torch.float32, # Loading the model with a lower precision leads to instable training, instead we use `torch.autocast` to facilitate mixed precision training
        **class_spec,
        **model_builder_kwargs
    )
    nn_model.eval()
    if not isinstance(nn_model, torch.nn.Module):
        raise TypeError(
            'Expected `model_builder` to return a tuple, where the first element'
            f'is an object inheriting from `torch.nn.Module`, but got `{type(nn_model)}`.'
        )
    
    # Prepare dataloader
    labels = None
    if data_index is not None:
        metadata = get_metadata(data_index)
        images = [p for p, s in zip(metadata["path"], metadata["split"]) if s == "test"]
        labels = [p for p, s in zip(metadata["label"], metadata["split"]) if s == "test"]
    else:
        labels, images = auto_find_images(input, **class_spec)
    if subsample is not None and subsample > 1:
        labels, images = labels[::subsample], images[::subsample]
    
    loader = builder.build_inference_dataloader(
        images=images,
        preprocess=model_preprocess,
        device=device,
        dtype=dtype,
        **dataloader_builder_kwargs
    )
    if not isinstance(loader, torch.utils.data.DataLoader):
        raise TypeError(
            'Expected `dataloader_builder` to return an objects'
            f'inheriting from `torch.utils.data.DataLoader`, but got `{type(loader)}.'
        )

    # Prepare augmentation
    # augmentation = builder.build_augmentation(dtype=dtype, **augmentation_builder_kwargs)
    # if not isinstance(augmentation, torchvision.transforms.Compose):
    #     raise TypeError(
    #         'Expected `augmentation_builder` to return an objects'
    #         f'inheriting from `torchvision.transforms.Compose`, but got `{type(augmentation)}.'
    #     )
    # debug_augmentation(
    #     augmentation=augmentation,
    #     dataset=loader.dataset,
    #     output_dir=output_dir,
    #     strict=True
    # )

    # criterion = builder.build_criterion(
    #     labels=labels,
    #     num_classes=class_spec["num_classes"], 
    #     device=device,
    #     dtype=dtype,
    #     **criterion_builder_kwargs
    # )
    # if not isinstance(criterion, torch.nn.modules.loss._Loss):
    #     raise TypeError(
    #         'Expected `criterion_builder` to return an object'
    #         f'inheriting from `torch.nn.modules.loss._Loss`, but got `{type(criterion)}.'
    #     )
    
    collector_cls_kwargs["additional_attributes"] = ["labels"] if labels is not None else None
    collector = collector_cls(**collector_cls_kwargs, **class_spec)
    
    idx = 0
    with torch.inference_mode(), torch.autocast(device_type=str(device)):
        for batch in TQDM(loader, desc="Running inference", unit="batch"):
            pred : torch.Tensor | list[torch.Tensor] = nn_model(model_preprocess(batch.to(device)))
            # pred_is_list = False
            # if isinstance(pred, (list, tuple)):
            #     pred_is_list = True
            idxs = slice(idx, idx + len(batch))
            idx += len(batch)
            # labs = torch.tensor(labels[idxs]).long() if labels is not None else None
            # if labs is not None:
            #     if not pred_is_list:
            #         loss = [criterion(p.unsqueeze(0), l.unsqueeze(0).unsqueeze(0)) for p, l in zip(pred, labs.to(device))]
            #     else:
            #        loss = [criterion([pi.unsqueeze(0) for pi in p], l.unsqueeze(0)) for p, l in zip(zip(*pred), labs.to(device))]
            #     loss = [
            #         l.item() if isinstance(l, torch.Tensor) else [li.item() for li in l] for l in loss
            #     ]
            # else:
            #     loss = None
            collector.collect(
                paths=images[idxs], 
                predictions=pred,
                labels=None if labels is None else labels[idxs],
                # loss=loss
            )
    del loader, nn_model

    collector.save_mini_metric_csv(os.path.join(output, name, "mini_metric.csv"), threshold=threshold)
    collector.evaluate(os.path.join(output, name))
            

def cli(description="Classify images with a trained model", **extra_kwargs):
    parser = ArgumentParser(
        prog="train",
        description=description,
        formatter_class=Formatter
    )

    # Optional YAML config support
    cfg_args = parser.add_argument_group("Config [optional]")
    cfg_args.add_argument(
        "--config", type=str, default=None, required=False,
        help="Path to a YAML config file; values act as defaults and are overridden by explicit CLI flags."
    )

    if extra_kwargs:
        for argname, kwargs in extra_kwargs.items():
            args = []
            if None in kwargs:
                args = kwargs.pop(None)
                if not hasattr(args, "__iter__") or isinstance(args, str):
                    args = [args]
                else:
                    args = list(args)
            args.insert(0, f'--{argname}')
            parser.add_argument(*args, **kwargs)

    input_args = parser.add_argument_group("Input [mandatory]")
    input_args.add_argument(
        "-i", "--input", type=str, 
        default=None, required=False,
        help=
        "Path to a directory containing a subdirectory for each class,\n" 
        "where the name of each subdirectory should correspond to the name of the class."
    )
    out_args = parser.add_argument_group("Output [optional]")
    out_args.add_argument(
        "-o", "--output", type=str, 
        default=None, required=False,
        help=
        "Root directory for all created files and directories.\n"
        "Default is current working directory ('.')."
    )
    out_args.add_argument(
        "-n", "--name", type=str, 
        default="predict", required=False,
        help=
        "Name of the output predictions.\n"
        "Default is 'predict'."
    )
    mod_args = parser.add_argument_group("Model [optional]")
    mod_args.add_argument(
        "-f", "--model_folder", type=str,
        default=None, required=False,
        help=
        "Path to folder created when training a model.\n"
        "This argument chooses defaults for 'model', 'weights' and 'class_spec',\n"
        "but will be superseded by these if they are manually specified as well."
    )
    mod_args.add_argument(
        "-m", "--model", type=str, dest="model_builder_kwargs.model_type",
        default=None, required=False,
        help=
        "Name of the model type from the torchvision model zoo (not case-sensitive):\n"
        "https://pytorch.org/vision/main/models.html#table-of-all-available-classification-weights)"
    )
    mod_args.add_argument(
        "-w", "--weights", type=str, dest="model_builder_kwargs.weights",
        default=None, required=False,
        help="Model weights used to initialize model before training."
    )
    mod_args.add_argument(
        "-C", "--class_spec", type=str, 
        default=None, required=False,
        help=
        "path to a JSON file containing the class name to index mapping and other\n"
        "important information for constructing models and dataloaders.\n"
        "If it doesn't exist, one will be created based on the directories found under `output` if it is set."
    )
    inf_args = parser.add_argument_group("Inference [optional]")
    inf_args.add_argument(
        "-t", "--threshold", type=float,
        default=None, required=False,
        help=
        "Confidence threshold for predictions.\n"
        "Used for mini_metrics csv.\n"
        "Default is 0 (always predict)."
    )
    inf_args.add_argument(
        "-D", "--data_index", type=str,
        default=None, required=False,
        help=
        "JSON file containing three arrays with keys 'path', 'split' and 'class'.\n"
        "The arrays should all have equal lengths and can be considered \"columns\" in a table.\n"
        "The 'split' column should contain values 'train', 'validation' or other,\n"
        "and the 'class' column' should contain the the class *names* (not indices) for each file/path."
    )
    inf_args.add_argument(
        "--batch_size", type=int, dest="dataloader_builder_kwargs.batch_size",
        default=None, required=False,
        help="Number of images used in each mini-batch for training/validation (default=16)."
    )
    inf_args.add_argument(
        "--size", type=int, dest="dataloader_builder_kwargs.resize_size",
        default=None, required=False,
        help="Size of the input images; width, height (default=256)."
    )
    cfg_args = parser.add_argument_group("Runtime [optional]")
    cfg_args.add_argument(
        "--subsample", type=int,
        default=None, required=False,
        help="Subsample the data for training and eval (useful for testing). Default is None (no subsampling)."
    )
    cfg_args.add_argument(
        "--device", type=str, 
        default=None, required=False,
        help='Device used for training (default="cuda:0").'
    )
    cfg_args.add_argument(
        "--dtype", type=str, 
        default=None, required=False,
        help=
        "PyTorch data type used for storing images for training/validation (default=bfloat16).\n" 
        "The model is always stored in float32, and training is done with autocasting."
    )
    cfg_args.add_argument(
        "--num_workers", type=int, dest="dataloader_builder_kwargs.num_workers",
        default=None, required=False,
        help="Number of workers used for the dataloaders. Default is number of CPU cores on your machine."
    )
    cfg_args.add_argument(
        "--seed", type=int, 
        default=None, required=False,
        help=
        "Set the initial seed for the RNG in the core Python library `random`.\n"
        "This is particularly important for reproducible train/validation splits."
    )
    cfg_args.add_argument(
        "-v", "--verbose", action="store_true", dest="collector_cls_kwargs.verbose",
        default=None, required=False,
        help="Print training statistics in the terminal."
    )
    cli_args = vars(parser.parse_args())

    # Build the three layers
    defaults_full = defaults_from_function(main) # Defaults defined in the function signature
    config_full = load_yaml_config(cli_args.pop("config")) # Arguments passed from config (empty if no config)
    cli_full = restructure_cli_args(cli_args) # Manual CLI arguments

    args = merge_dicts(defaults_full, config_full, cli_full)

    # Validate required arguments
    if args.get("input") is None:
        raise SystemExit("error: the following arguments are required: --input (via CLI or config)")
    
    model_folder = args.pop("model_folder", None)
    if model_folder is not None:
        args = assign_model_from_folder(model_folder, args)
    
    return args


def run():
    main(**cli())

if __name__ == "__main__":  
    run()
