import os
import random
import sys
from argparse import ArgumentParser
from typing import Any

import numpy as np
import torch
import torchvision

from mini_trainer import Formatter
from mini_trainer.builders import AutoEmbedder, BaseBuilder
from mini_trainer.config import (defaults_from_function, dump_resolved_config,
                                 load_yaml_config, merge_dicts,
                                 restructure_cli_args)
from mini_trainer.utils import increment_name_dir
from mini_trainer.utils.augmentation import debug_augmentation
from mini_trainer.utils.data import auto_find_images, get_metadata
from mini_trainer.utils.logging import BaseResultCollector


def main(
        input : str,
        output : str | None=None,
        class_spec : str | None=None,
        name: str | None=None,
        device : str="cuda:0",
        dtype : str="bfloat16",
        seed : int | None=None,
        builder : type[BaseBuilder]=BaseBuilder,
        collector_cls : type[BaseResultCollector]=BaseResultCollector,
        spec_model_dataloader_kwargs : dict[str, Any]={},
        model_builder_kwargs : dict[str, Any]={
            "model_type" : "efficientnet_v2_s",
            "weights" : None,
            "fine_tune" : False,
            "hidden" : True,
            "droprate" : 0.1,
            "normalized" : True
        },
        dataloader_builder_kwargs : dict[str, Any]={
            "batch_size" : 16,
            "resize_size" : 256, 
            "train_proportion" : 0.9
        },
        augmentation_builder_kwargs : dict[str, Any]={},
        criterion_builder_kwargs : dict[str, Any]={
            "weighted" : False,
            "label_smoothing" : 0.1
        },
        collector_cls_kwargs : dict[str, Any]={}
    ):
    """
    Predict with a classifier.

    Args:
        input: Path to a directory containing a subdirectory for each class, where
            each subdirectory's name corresponds to the class name.
            It is also possible to pass the path to a parquet as generated by `gbifxdl` instead of a directory.
        output: Root directory for all created files and directories.
            Default is current working directory ``'.'``.
        class_spec: Path to a JSON file containing the mapping from class names to indices
            and other important information necessary to construct compatible models and dataloaders.
            If the file does not exist, it will be created based on subdirectories
            found under `output` if it is set. Default is 'class_index.json'.
        epochs: Number of training epochs. Default is 15.
        name: Name of the output model. If not provided, a descriptive name
            will be inferred from other arguments. Default is ``None``.
        device: Device used for training (e.g., ``'cuda:0'``, ``'cpu'``). Default is ``'cuda:0'``.
        dtype: PyTorch data type for images during training and validation (e.g., ``'bfloat16'``). 
            The model parameters are always stored in float32 with training AMP. 
            Default is ``'bfloat16'``.
        seed: Initial seed for Python's random number generator to ensure reproducibility,
            especially for train/validation splits. Default is ``None``.
        builder: An object inheriting from ``mini_trainer.builders.BaseBuilder``. 
            This object is responsible for instantiating the model, dataloader, augmentation, 
            optimizer, scaler, EMA, criterion (loss function) and learning rate scheduler.
        **kwargs:
            Additional arguments are passed to the various builder methods.
            See ``mini_trainer.builders.BaseBuilder`` for details.
    """
    orig_args = locals()
    # Prepare state    
    if seed is not None:
        random.seed(seed)
        np.random.seed(seed)
        torch.manual_seed(seed)
    if name is None:
        name = "train"
    name = increment_name_dir(name, output)

    input = os.path.abspath(input)
    output_dir = None if output is None else os.path.abspath(os.path.join(output, name))
    if output_dir is not None:
        try:
            os.makedirs(output_dir, exist_ok=False)
        except OSError as e:
            e.add_note(f"Training output directory already exists: {output_dir}. Perhaps a run of with the `{name=}` already exists?")
    
    weight_output_dir = None if output_dir is None else os.path.abspath(os.path.join(output_dir, "weights"))
    if weight_output_dir is not None:
        try:
            os.makedirs(weight_output_dir, exist_ok=False)
        except OSError as e:
            e.add_note(f"Training weight directory already exists: {weight_output_dir}. Perhaps a run of with the `{name=}` already exists?")

    device : torch.device = torch.device(device)
    dtype : torch.dtype = getattr(torch, dtype.removeprefix("torch.").strip().lower())

    # Dump resolved configuration using locals and normalized values
    dump_resolved_config(
        output_dir=output_dir,
        fn=main,
        local_vars=orig_args,
        overrides={
            "input": input,
            "output": output_dir,
            "device": device,
            "dtype": dtype,
            "name": name,
        },
    )

    # Load additional information for model and dataloader instantiation
    # e.g. number of classes, class-to-index dictionary
    class_spec = builder.class_spec(
        path=class_spec if class_spec is not None else os.path.join(output_dir, "class_spec.json"), 
        dir=input,
        **spec_model_dataloader_kwargs
    )

    # Prepare model
    nn_model, model_preprocess = builder.build_model(
        device=device, 
        dtype=torch.float32, # Loading the model with a lower precision leads to instable training, instead we use `torch.autocast` to facilitate mixed precision training
        **class_spec,
        **model_builder_kwargs
    ) 
    if not isinstance(nn_model, torch.nn.Module):
        raise TypeError(
            'Expected `model_builder` to return a tuple, where the first element'
            f'is an object inheriting from `torch.nn.Module`, but got `{type(nn_model)}`.'
        )
    
    # Prepare dataloader
    if "data_index" in dataloader_builder_kwargs:
        metadata = get_metadata(dataloader_builder_kwargs["data_index"])
        images = [p for p, s in zip(metadata["path"], metadata["split"]) if s == "test"]
        labels = [p for p, s in zip(metadata["class"], metadata["split"]) if s == "test"]
    else:
        labels, images = auto_find_images(input, **class_spec)
    loader = builder.build_inference_dataloader(
        images=images,
        preprocess=model_preprocess,
        device=device,
        dtype=dtype,
        **dataloader_builder_kwargs
    )
    if not isinstance(loader, torch.utils.data.DataLoader):
        raise TypeError(
            'Expected `dataloader_builder` to return an objects'
            f'inheriting from `torch.utils.data.DataLoader`, but got `{type(loader)}.'
        )

    # # Prepare augmentation
    # augmentation = builder.build_augmentation(dtype=dtype, **augmentation_builder_kwargs)
    # if not isinstance(augmentation, torchvision.transforms.Compose):
    #     raise TypeError(
    #         'Expected `augmentation_builder` to return an objects'
    #         f'inheriting from `torchvision.transforms.Compose`, but got `{type(augmentation)}.'
    #     )
    # debug_augmentation(
    #     augmentation=augmentation,
    #     dataset=loader.dataset,
    #     output_dir=output_dir,
    #     strict=True
    # )

    criterion = builder.build_criterion(
        labels=labels,
        num_classes=class_spec["num_classes"], 
        device=device,
        dtype=dtype,
        **criterion_builder_kwargs
    )
    if not isinstance(criterion, torch.nn.modules.loss._Loss):
        raise TypeError(
            'Expected `criterion_builder` to return an object'
            f'inheriting from `torch.nn.modules.loss._Loss`, but got `{type(criterion)}.'
        )
    
    collector = collector_cls(**collector_cls_kwargs, **class_spec)
    
    idx = 0
    with torch.inference_mode(), torch.autocast(device_type=str(device)):
        for batch in loader:
            pred = nn_model(model_preprocess(batch.to(device)))
            idxs = slice(idx, idx+len(batch))
            labs = torch.tensor(labels[idxs]).long() if labels is not None else None
            if labs is not None:
                loss = criterion(pred, labs.to(device))
            else:
                loss = None
            collector.collect(
                paths=images[idxs], 
                predictions=pred,
                labels=labs,
                loss=loss
            )
    del loader, nn_model, criterion

    collector.evaluate(output)
    collector.save_mini_metric_csv(os.path.join(output, f"{name}_mini_metric.csv"))
            

def cli(description="Classify images with a trained model", **extra_kwargs):
    parser = ArgumentParser(
        prog="train",
        description=description,
        formatter_class=Formatter
    )

    # Optional YAML config support
    cfg_args = parser.add_argument_group("Config [optional]")
    cfg_args.add_argument(
        "--config", type=str, default=None, required=False,
        help="Path to a YAML config file; values act as defaults and are overridden by explicit CLI flags."
    )

    if extra_kwargs:
        for argname, kwargs in extra_kwargs.items():
            args = []
            if None in kwargs:
                args = kwargs.pop(None)
                if not hasattr(args, "__iter__") or isinstance(args, str):
                    args = [args]
                else:
                    args = list(args)
            args.insert(0, f'--{argname}')
            parser.add_argument(*args, **kwargs)

    input_args = parser.add_argument_group("Input [mandatory]")
    input_args.add_argument(
        "-i", "--input", type=str, default=None, required=False,
        help=
        "Path to a directory containing a subdirectory for each class,\n" 
        "where the name of each subdirectory should correspond to the name of the class."
    )
    out_args = parser.add_argument_group("Output [optional]")
    out_args.add_argument(
        "-o", "--output", type=str, default=None, required=False,
        help=
        "Root directory for all created files and directories.\n"
        "Default is current working directory ('.')."
    )
    out_args.add_argument(
        "-n", "--name", type=str, default=None, required=False,
        help=
        "Name of the output model.\n"
        "If not provided, a helpful name will be inferred from the other arguments."
    )
    mod_args = parser.add_argument_group("Model [optional]")
    mod_args.add_argument(
        "-m", "--model", type=str, dest="model_builder_kwargs.model_type",
        default=None, required=False,
        help=
        "Name of the model type from the torchvision model zoo (not case-sensitive):\n"
        "https://pytorch.org/vision/main/models.html#table-of-all-available-classification-weights)"
    )
    mod_args.add_argument(
        "-w", "--weights", type=str, dest="model_builder_kwargs.weights",
        default=None, required=False,
        help="Model weights used to initialize model before training."
    )
    mod_args.add_argument(
        "-C", "--class_spec", type=str, default=None, required=False,
        help=
        "path to a JSON file containing the class name to index mapping and other\n"
        "important information for constructing models and dataloaders.\n"
        "If it doesn't exist, one will be created based on the directories found under `output` if it is set."
    )
    inf_args = parser.add_argument_group("Inference [optional]")
    inf_args.add_argument(
        "-D", "--data_index", type=str, dest="dataloader_builder_kwargs.data_index",
        default=None, required=False,
        help=
        "JSON file containing three arrays with keys 'path', 'split' and 'class'.\n"
        "The arrays should all have equal lengths and can be considered \"columns\" in a table.\n"
        "The 'split' column should contain values 'train', 'validation' or other,\n"
        "and the 'class' column' should contain the the class *names* (not indices) for each file/path."
    )
    inf_args.add_argument(
        "--batch_size", type=int, dest="dataloader_builder_kwargs.batch_size",
        default=None, required=False,
        help="Number of images used in each mini-batch for training/validation (default=16)."
    )
    inf_args.add_argument(
        "--size", type=int, dest="dataloader_builder_kwargs.resize_size",
        default=None, required=False,
        help="Size of the input images; width, height (default=256)."
    )
    cfg_args = parser.add_argument_group("Runtime [optional]")
    cfg_args.add_argument(
        "--subsample", type=int, dest="dataloader_builder_kwargs.subsample",
        default=None, required=False,
        help="Subsample the data for training and eval (useful for testing). Default is None (no subsampling)."
    )
    cfg_args.add_argument(
        "--device", type=str, default=None, required=False,
        help='Device used for training (default="cuda:0").'
    )
    cfg_args.add_argument(
        "--dtype", type=str, default=None, required=False,
        help=
        "PyTorch data type used for storing images for training/validation (default=bfloat16).\n" 
        "The model is always stored in float32, and training is done with autocasting."
    )
    cfg_args.add_argument(
        "--num_workers", type=int, dest="dataloader_builder_kwargs.num_workers",
        default=None, required=False,
        help="Number of workers used for the dataloaders. Default is number of CPU cores on your machine."
    )
    cfg_args.add_argument(
        "--seed", type=int, default=None, required=False,
        help=
        "Set the initial seed for the RNG in the core Python library `random`.\n"
        "This is particularly important for reproducible train/validation splits."
    )
    cfg_args.add_argument(
        "-v", "--verbose", action="store_true", dest="logger_builder_kwargs.verbose",
        default=None, required=False,
        help="Print training statistics in the terminal."
    )
    cli_args = vars(parser.parse_args())

    # Build the three layers
    defaults_full = defaults_from_function(main) # Defaults defined in the function signature
    config_full = load_yaml_config(cli_args.pop("config")) # Arguments passed from config (empty if no config)
    cli_full = restructure_cli_args(cli_args) # Manual CLI arguments

    args = merge_dicts(defaults_full, config_full, cli_full)

    # Validate required arguments
    if args.get("input") is None:
        raise SystemExit("error: the following arguments are required: --input (via CLI or config)")

    # Set reasonable default name for unspecified CLI inference runs
    if args.get("name") is None:
        # args["name"] = 
        pass
    
    return args


def run():
    sys.exit(main(**cli()))

if __name__ == "__main__":  
    run()
